# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 12:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170824_1122'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
